Models/ErrorViewModel.cs
namespace CRUDPractica.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/PersonModel.cs
namespace CRUDPractica.Models
{
    public class PersonModel
    {
       public int id { get; set; } 
       public string first_name { get; set; } 
       public string last_name { get; set; }
       public string? birth_date { get; set; } 
       public int gender { get; set; } 
       public int? status { get; set; } 
       public string? create_date { get; set; } 
       public string? edit_date { get;set; }
    }
}

Controllers/HomeController.cs
using CRUDPractica.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CRUDPractica.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PersonaController.cs
using CRUDPractica.Datos;
using CRUDPractica.Models;
using Microsoft.AspNetCore.Mvc;

namespace CRUDPractica.Controllers
{
    public class PersonaController : Controller
    {
        PersonDatos person = new PersonDatos();
        public IActionResult Listar()
        {
            //Vista que mostrara a las personas
            var oLista = person.Listar();
            return View(oLista);
        }

        public IActionResult Guardar()
        {
            //Vista para guardar una persona
            return View();
        }

        [HttpPost]
        public IActionResult Guardar(PersonModel oPersona)
        {
            //Vista para guardar una persona en BD
            var respuesta = person.Guardar(oPersona);

            if (respuesta)
            {
                return RedirectToAction("Listar");
            }
            else
                return View();

        }

        public IActionResult Editar(int id)
        {
            var person2 = person.Obtener(id);
            //Vista para guardar una persona
            return View(person2);
        }

        [HttpPost]
        public IActionResult Editar(PersonModel oPersona)
        {
            //Vista para guardar una persona en BD
            var respuesta = person.Editar(oPersona);

            if (respuesta)
            {
                return RedirectToAction("Listar");
            }
            else
                return View();

        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Persona/Editar.cshtml
@model PersonModel
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Editar Persona
    </div>
    <div class="card-body">
        <form asp-action="Editar" asp-controller="Persona" method="post">
            <input asp-for="id" type="hidden" class="form-control">
            <div class="mb-3">
                <label class="form-label">Nombres</label>
                <input asp-for="first_name" type="text" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">Apellidos</label>
                <input asp-for="last_name" type="text" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">Apellidos</label>
                <input asp-for="gender" type="text" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
            <a asp-action="Listar" asp-controller="Persona" class="btn btn-warning">Volver a lista</a>
        </form>
    </div>
</div>

Views/Persona/Guardar.cshtml
@model PersonModel
@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Crear Persona
    </div>
    <div class="card-body">
        <form asp-action="Guardar" asp-controller="Persona" method="post">
            <div class="mb-3">
                <label  class="form-label">Nombres</label>
                <input asp-for="first_name" type="text" class="form-control">
            </div>
            <div class="mb-3">
                <label  class="form-label">Apellidos</label>
                <input asp-for="last_name" type="text" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">Apellidos</label>
                <input asp-for="gender" type="text" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
            <a asp-action="Listar" asp-controller="Persona" class="btn btn-warning">Volver a lista</a>
        </form>
    </div>
</div>

Views/Persona/Listar.cshtml
@model List<PersonModel>
@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Lista de Personas
    </div>
    <div class="card-body">
        <a asp-action="Guardar" asp-controller="Persona" class="btn btn-success">Agregar Persona</a>
        <hr/>
        <table class="table table-bordered">
            <thead>
                <th>Nombre</th>
                <th>Apellidos</th>
                <th>Fecha nacimiento</th>
                <th>Genero</th>
                <th>Estado</th>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.first_name</td>
                        <td>@item.last_name</td>
                        <td>@item.birth_date</td>
                        <td>@item.gender</td>
                        <td>@item.status</td>
                        <td><a asp-action="Editar" asp-controller="Persona" class="btn btn-primary  btn-sm" asp-route-id="@item.id" >Editar</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/PersonaController1/Guardar.cshtml
@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Crear Persona
    </div>
    <div class="card-body">
        <form>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Email address</label>
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1">
            </div>
            <div class="mb-3 form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

Views/PersonaController1/Listar.cshtml
@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Listar</h1>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUDPractica</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CRUDPractica.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRUDPractica</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CRUDPractica - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>